apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-secret
type: Opaque
stringData:
  username: admin
  password: 
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 
  dataLIF:  
  backendName: ontap-nas
  svm: Anthos 
  credentials:
    name: backend-tbc-ontap-nas-secret
